---
title: Beer n' Play
timezone: Europe/Stockholm
collections:
  food:
    title: Food
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
phone: 1262
email: bar@beernplay.se
sass:
  sass_dir: assets/css
