---
title: Beer n' Play
timezone: Europe/Stockholm
collections:
  sides:
    title: Bar Menu
    output: false
    type: food
    position: 2
    picture: "/uploads/fries-sm"
  burgers:
    title: Burgers
    output: false
    info: Fries included with all burgers.<br> Sweet potato fries 15:- extra
    type: food
    position: 4
  desserts:
    title: Desserts
    output: false
    type: food
    position: 8
    picture: "/uploads/nutellaroll-sm"
  dips:
    title: Dips
    output: false
    type: food
    position: 3
  sausages:
    title: Korv
    output: false
    info: "All hot dogs are served with fries.\nSweet potato fries 15:- extra. "
    type: food
    position: 1
    picture: "/uploads/frankfurter-sm"
  pizza:
    title: Pizza
    output: false
    type: food
    position: 7
  posts:
    title: Posts
    output: true
  sallads:
    title: Sallads
    output: false
    type: food
    position: 5
    picture: "/uploads/asiancaesar2-sm"
  specials:
    title: Specials
    output: false
    type: food
    position: 6
    picture: "/uploads/bookmaker-sm"
  uploads:
    title: Uploads
    output: true
description: Craft beer, fun and food. New bar on Hornsgatan 138, Stockholm.
phone: '08-42050569'
email: bar@beernplay.se
address: Hornsgatan 138 Stockholm
maps: https://goo.gl/maps/Lzw12C63Pt6gnJ6E7
facebook: https://www.facebook.com/beernplay/
instagram: https://www.instagram.com/beernplay/
untappd: https://untappd.com/v/beer-n-play/8976477
sass:
  sass_dir: assets/css
