---
title: Beer n' Play
timezone: Europe/Stockholm
collections:
  burgers:
    title: Burgers
    output: false
    description: Heppreef
    type: food
  pizza:
    title: Pizza
    output: false
    type: food
  posts:
    title: Posts
    output: true
  sallads:
    title: Sallads
    output: false
    type: food
  uploads:
    title: Uploads
    output: true
phone: 1262
email: bar@beernplay.se
sass:
  sass_dir: assets/css
