---
title: Beer n' Play
timezone: Europe/Stockholm
collections:
  burgers:
    title: Burgers
    output: false
    description: Our burgers are made with love and cooked to perfection. Enjoy!
    info: Fries included with all burgers.<br> Sweet potato fries 15:- extra
    type: food
    position: 4
    picture: "/assets/images/burger1-s.jpg"
  desserts:
    title: Desserts
    output: false
    type: food
    position: 8
  dips:
    title: Dips
    output: false
    type: food
    position: 3
  sausages:
    title: Korv
    output: false
    info: Don't forget sides!
    type: food
    position: 1
    picture: "/assets/images/frankfurter-s.jpg"
  pizza:
    title: Pizza
    output: false
    type: food
    position: 7
    picture: "/assets/images/primavera-s.jpg"
    description: We make genuine Pizza Napolitana with a traditional thick sourdough
      crust. Put pizza in mouth now.
  posts:
    title: Posts
    output: true
  sallads:
    title: Sallads
    output: false
    type: food
    position: 5
    picture: "/assets/images/asiancaesar2-s.jpg"
  sides:
    title: Sides
    output: false
    type: food
    position: 2
    picture: "/assets/images/fries-s.jpg"
  specials:
    title: Specials
    output: false
    type: food
    position: 6
    picture: "/assets/images/bookmaker-s.jpg"
  uploads:
    title: Uploads
    output: true
phone: 1262
email: bar@beernplay.se
sass:
  sass_dir: assets/css
