---
title: Beer n' Play
timezone: Europe/Stockholm
collections:
  pizza:
    title: Pizza
    position:
    type: food
    output: false
  burgers:
    title: Burgers
    description: Heppreef
    type: food
    output: false
  sallads:
    title: Sallads
    type: food
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
phone: 1262
email: bar@beernplay.se
sass:
  sass_dir: assets/css
