---
title: Beer n' Play
timezone: Europe/Stockholm
collections:
  burgers:
    title: Burgers
    output: false
    description: Fries included with all burgers.<br> Sweet potato fries 15:- extra
    type: food
    position: 4
  desserts:
    title: Desserts
    output: false
    type: food
    position: 8
  dips:
    title: Dips
    output: false
    type: food
    position: 3
  sausages:
    title: Korv <span>(140g) Don't forget sides!</span>
    output: false
    type: food
    position: 1
  pizza:
    title: Pizza
    output: false
    type: food
    position: 7
  posts:
    title: Posts
    output: true
  sallads:
    title: Sallads
    output: false
    type: food
    position: 5
  sides:
    title: Side orders
    output: false
    type: food
    position: 2
  specials:
    title: Specials
    output: false
    type: food
    position: 6
  uploads:
    title: Uploads
    output: true
phone: 1262
email: bar@beernplay.se
sass:
  sass_dir: assets/css
