---
title: Beer n' Play
timezone: Europe/Stockholm
collections:
  sides:
    title: Bar Menu
    output: false
    lang: en
    type: food
    position: 7
  sides_sv:
    title: Barmeny
    output: false
    lang: sv
    type: food
    position: 7
  burgers:
    title: Burgers
    output: false
    lang: en
    info: Fries included with all burgers.<br> Sweet potato fries 15:- extra
    type: food
    position: 3
  desserts:
    title: Desserts
    output: false
    lang: en
    type: food
    position: 9
  dips_sv:
    title: Dipp
    output: false
    lang: sv
    type: food
    position: 8
  dips:
    title: Dips
    output: false
    lang: en
    type: food
    position: 8
  desserts_sv:
    title: Efterrätter
    output: false
    lang: sv
    type: food
    position: 9
  burgers_sv:
    title: Hamburgare
    output: false
    lang: sv
    info: Pommes frites ingår med alla burgare.<br>Sötpotatispommes 15:- extra
    type: food
    position: 3
  sausages_sv:
    title: Korv
    output: false
    lang: sv
    info: |-
      Pommes frites ingår med alla korvar.
      Sötpotatispommes 15:- extra
    type: food
    position: 2
  milkshakes_sv:
    title: Lyxshakes
    output: false
    lang: sv
    type: food
    position: 10
  milkshakes:
    title: Milkshakes
    output: false
    lang: en
    type: food
    position: 10
  pasta:
    title: Pasta
    output: false
    lang: en
    type: food
    position: 4
  pizza:
    title: Pizza Napoletana
    output: false
    lang: en
    type: food
    position: 1
  pizza_sv:
    title: Pizza Napoletana
    output: false
    lang: sv
    type: food
    position: 1
  posts:
    title: Posts
    output: true
  sallads_sv:
    title: Sallader
    output: false
    lang: sv
    type: food
    position: 5
  sallads:
    title: Sallads
    output: false
    lang: en
    type: food
    position: 5
  specials:
    title: Specials
    output: false
    lang: en
    type: food
    position: 6
  specials_sv:
    title: Specials
    output: false
    lang: sv
    type: food
    position: 6
  uploads:
    title: Uploads
    output: true
description: Craft beer, fun and food. New bar on Hornsgatan 138, Stockholm.
description-sv: Hantverksöl, sport, spel och god mat. Ny öl- och sportbar på  Hornsgatan
  138, Stockholm.
phone: '08-42050569'
email: bar@beernplay.se
address: Hornsgatan 138 Stockholm
maps: https://goo.gl/maps/Lzw12C63Pt6gnJ6E7
facebook: https://www.facebook.com/beernplay/
instagram: https://www.instagram.com/beernplay/
untappd: https://untappd.com/v/beer-n-play/8976477
sass:
  sass_dir: assets/css
