---
title: Beer n' Play
timezone: Europe/Stockholm
collections:
  burgers:
    title: Burgers
    output: false
    description: Our burgers are made with love and cooked to perfection. Enjoy!
    info: Fries included with all burgers.<br> Sweet potato fries 15:- extra
    type: food
    position: 4
    picture: "/uploads/burger1-sm"
  desserts:
    title: Desserts
    output: false
    type: food
    position: 8
  dips:
    title: Dips
    output: false
    type: food
    position: 3
  sausages:
    title: Korv
    output: false
    info: Don't forget sides!
    type: food
    position: 1
    picture: "/uploads/frankfurter-sm"
  pizza:
    title: Pizza
    output: false
    type: food
    position: 7
    picture: "/uploads/primavera-sm"
    description:
      We make genuine Pizza Napolitana with a traditional thick sourdough
      crust. Put pizza in mouth now.
  posts:
    title: Posts
    output: true
  sallads:
    title: Sallads
    output: false
    type: food
    position: 5
    picture: "/uploads/asiancaesar2-sm"
  sides:
    title: Sides
    output: false
    type: food
    position: 2
    picture: "/uploads/fries-sm"
  specials:
    title: Specials
    output: false
    type: food
    position: 6
    picture: "/uploads/bookmaker-sm"
  uploads:
    title: Uploads
    output: true
phone: 08-420 505 69
email: bar@beernplay.se
address: Beern n' Play, Hornsgatan 138 Stockholm
maps: https://goo.gl/maps/Lzw12C63Pt6gnJ6E7
facebook: https://www.facebook.com/beernplay/
instagram: https://www.instagram.com/beernplay/
untappd: https://untappd.com/v/beer-n-play/8976477
sass:
  sass_dir: assets/css
